### ISSUE TITLE
Cannot build with LLVM 3.1-SVN

### ISSUE THREAD

**Issue by sebastianbergmann** [weyrick/roadsend-php-raven#3]
```
$ cmake .
-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/lib64/ccache/gcc
-- Check for working C compiler: /usr/lib64/ccache/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- PROJECT_SOURCE_DIR: /usr/local/src/raven
-- CMAKE_MODULE_PATH: /usr/local/src/raven/cmake/modules
-- RPHP_INCLUDE_DIR: /usr/local/src/raven/include
-- RPHP_LIB_DIR: /usr/local/src/raven/lib
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- Boost version: 1.47.0
-- ICU version: 4.6
-- LLVM clang++ found at: /usr/local/bin/clang++
-- LLVM version: 3.1svn
-- LLVM CXX flags: -I/usr/local/include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- LLVM LD flags: -L/usr/local/lib  -lpthread -ldl -lm
-- LLVM core libs: -lLLVMLinker -lLLVMTransformUtils -lLLVMipa -lLLVMAnalysis -lLLVMTarget -lLLVMMC -lLLVMObject -lLLVMArchive -lLLVMBitWriter -lLLVMBitReader -lLLVMCore -lLLVMSupport
-- LLVM support libs: -lLLVMSupport
-- LLVM JIT libs: -lLLVMBitWriter -lLLVMLinker -lLLVMArchive -lLLVMBitReader -lLLVMX86AsmParser -lLLVMX86Disassembler -lLLVMX86CodeGen -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMMCParser -lLLVMX86Desc -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMJIT -lLLVMRuntimeDyld -lLLVMExecutionEngine -lLLVMCodeGen -lLLVMScalarOpts -lLLVMInstCombine -lLLVMTransformUtils -lLLVMipa -lLLVMAnalysis -lLLVMTarget -lLLVMMC -lLLVMObject -lLLVMCore -lLLVMSupport
-- LLVM JIT objs: 
-- Found LLVM: /usr/local/include
-- GMP libs: /usr/lib64/libgmp.so /usr/lib64/libgmpxx.so
-- Found GMP: /usr/include 
-- Found Doxygen: /usr/bin/doxygen 
-- 3rd party: tinyxml check
-- runtime check
-- c-runtime check
-- compiler: analysis check
-- compiler: IR check
-- CLI frontend check
-- HTTP frontend check
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/src/raven


$ make
Scanning dependencies of target tinyxml
[  1%] Building CXX object 3rdparty/tinyxml/CMakeFiles/tinyxml.dir/tinyxml.cpp.o
[  2%] Building CXX object 3rdparty/tinyxml/CMakeFiles/tinyxml.dir/tinyxmlerror.cpp.o
[  4%] Building CXX object 3rdparty/tinyxml/CMakeFiles/tinyxml.dir/tinyxmlparser.cpp.o
Linking CXX static library libtinyxml.a
[  4%] Built target tinyxml
Scanning dependencies of target rphp-runtime
[  5%] Building CXX object runtime/CMakeFiles/rphp-runtime.dir/pErrorManager.cpp.o
[  7%] Building CXX object runtime/CMakeFiles/rphp-runtime.dir/pSupport.cpp.o
[  8%] Building CXX object runtime/CMakeFiles/rphp-runtime.dir/pVar.cpp.o
[ 10%] Building CXX object runtime/CMakeFiles/rphp-runtime.dir/pVarOperators.cpp.o
[ 11%] Building CXX object runtime/CMakeFiles/rphp-runtime.dir/pTypeOperators.cpp.o
[ 13%] Building CXX object runtime/CMakeFiles/rphp-runtime.dir/pResource.cpp.o
[ 14%] Building CXX object runtime/CMakeFiles/rphp-runtime.dir/pHash.cpp.o
[ 16%] Building CXX object runtime/CMakeFiles/rphp-runtime.dir/pObject.cpp.o
[ 17%] Building CXX object runtime/CMakeFiles/rphp-runtime.dir/pClass.cpp.o
[ 19%] Building CXX object runtime/CMakeFiles/rphp-runtime.dir/pRuntimeEngine.cpp.o
[ 20%] Building CXX object runtime/CMakeFiles/rphp-runtime.dir/pOutputBuffer.cpp.o
[ 22%] Building CXX object runtime/CMakeFiles/rphp-runtime.dir/pOutputManager.cpp.o
[ 23%] Building CXX object runtime/CMakeFiles/rphp-runtime.dir/pClassManager.cpp.o
[ 25%] Building CXX object runtime/CMakeFiles/rphp-runtime.dir/pFunctionManager.cpp.o
[ 26%] Building CXX object runtime/CMakeFiles/rphp-runtime.dir/pFunction.cpp.o
[ 28%] Building CXX object runtime/CMakeFiles/rphp-runtime.dir/pExtBase.cpp.o
[ 29%] Building CXX object runtime/CMakeFiles/rphp-runtime.dir/pExtManager.cpp.o
[ 31%] Building CXX object runtime/CMakeFiles/rphp-runtime.dir/standard/pStandardExt.cpp.o
Linking CXX shared library librphp-runtime.so
[ 31%] Built target rphp-runtime
Scanning dependencies of target rphp-pVar-speed
[ 32%] Building CXX object runtime/test/CMakeFiles/rphp-pVar-speed.dir/rphp-pVar-speed.cpp.o
Linking CXX executable rphp-pVar-speed
[ 32%] Built target rphp-pVar-speed
Scanning dependencies of target rphp-sizes
[ 34%] Building CXX object runtime/test/CMakeFiles/rphp-sizes.dir/rphp-sizes.cpp.o
Linking CXX executable rphp-sizes
[ 34%] Built target rphp-sizes
Scanning dependencies of target c-runtime-ir
[ 35%] Generating ../lib/c-runtime.bc
[ 37%] building C runtime IR
[ 37%] Built target c-runtime-ir
Scanning dependencies of target lemon-pg
[ 38%] Building C object compiler/analysis/CMakeFiles/lemon-pg.dir/grammar_src/lemon.c.o
Linking C executable lemon-pg
[ 38%] Built target lemon-pg
[ 40%] Generating rphp_grammar.cpp
106 parsing conflicts.
Scanning dependencies of target rphp-lexer-gen
[ 41%] Building CXX object compiler/analysis/CMakeFiles/rphp-lexer-gen.dir/lexer_src/rphp-lexer-gen.cpp.o
Linking CXX executable rphp-lexer-gen
[ 41%] Built target rphp-lexer-gen
[ 43%] Generating rphp_lang_lexer.h, rphp_dq_lexer.h
Scanning dependencies of target rphp-analysis
[ 44%] Building CXX object compiler/analysis/CMakeFiles/rphp-analysis.dir/rphp_grammar.cpp.o
[ 46%] Building CXX object compiler/analysis/CMakeFiles/rphp-analysis.dir/pAST.cpp.o
[ 47%] Building CXX object compiler/analysis/CMakeFiles/rphp-analysis.dir/pBaseVisitor.cpp.o
[ 49%] Building CXX object compiler/analysis/CMakeFiles/rphp-analysis.dir/pBaseTransformer.cpp.o
[ 50%] Building CXX object compiler/analysis/CMakeFiles/rphp-analysis.dir/pParseContext.cpp.o
[ 52%] Building CXX object compiler/analysis/CMakeFiles/rphp-analysis.dir/pSourceFile.cpp.o
[ 53%] Building CXX object compiler/analysis/CMakeFiles/rphp-analysis.dir/pLexer.cpp.o
[ 55%] Building CXX object compiler/analysis/CMakeFiles/rphp-analysis.dir/pParser.cpp.o
[ 56%] Building CXX object compiler/analysis/CMakeFiles/rphp-analysis.dir/pSourceModule.cpp.o
[ 58%] Building CXX object compiler/analysis/CMakeFiles/rphp-analysis.dir/pPass.cpp.o
[ 59%] Building CXX object compiler/analysis/CMakeFiles/rphp-analysis.dir/pPassManager.cpp.o
[ 61%] Building CXX object compiler/analysis/CMakeFiles/rphp-analysis.dir/passes/CheckMemoryManagement.cpp.o
[ 62%] Building CXX object compiler/analysis/CMakeFiles/rphp-analysis.dir/passes/SimplifyStrings.cpp.o
[ 64%] Building CXX object compiler/analysis/CMakeFiles/rphp-analysis.dir/passes/Desugar.cpp.o
[ 65%] Building CXX object compiler/analysis/CMakeFiles/rphp-analysis.dir/passes/DumpAST.cpp.o
[ 67%] Building CXX object compiler/analysis/CMakeFiles/rphp-analysis.dir/passes/DumpStats.cpp.o
[ 68%] Building CXX object compiler/analysis/CMakeFiles/rphp-analysis.dir/passes/Split_Builtins.cpp.o
[ 70%] Building CXX object compiler/analysis/CMakeFiles/rphp-analysis.dir/passes/Early_Lower_Loops.cpp.o
[ 71%] Building CXX object compiler/analysis/CMakeFiles/rphp-analysis.dir/passes/Lower_Binary_Op.cpp.o
[ 73%] Building CXX object compiler/analysis/CMakeFiles/rphp-analysis.dir/passes/Lower_Conditional_Expr.cpp.o
[ 74%] Building CXX object compiler/analysis/CMakeFiles/rphp-analysis.dir/passes/Lower_Control_Flow.cpp.o
[ 76%] Building CXX object compiler/analysis/CMakeFiles/rphp-analysis.dir/passes/MainFunction.cpp.o
Linking CXX static library librphp-analysis.a
[ 77%] Built target rphp-analysis
Scanning dependencies of target rphp-llvm-ir
[ 79%] Building CXX object compiler/IR/CMakeFiles/rphp-llvm-ir.dir/pGenerator.cpp.o
[ 80%] Building CXX object compiler/IR/CMakeFiles/rphp-llvm-ir.dir/pGenSupport.cpp.o
[ 82%] Building CXX object compiler/IR/CMakeFiles/rphp-llvm-ir.dir/pIRHelper.cpp.o
/usr/local/src/raven/compiler/IR/pIRHelper.cpp: In member function ‘llvm::Constant* rphp::IR::pIRHelper::byteArrayConstant(const llvm::StringRef&)’:
/usr/local/src/raven/compiler/IR/pIRHelper.cpp:214:74: error: no matching function for call to ‘llvm::ConstantArray::get(llvm::LLVMContext&, const llvm::StringRef&, bool)’
/usr/local/src/raven/compiler/IR/pIRHelper.cpp:214:74: note: candidate is:
/usr/local/include/llvm/Constants.h:354:20: note: static llvm::Constant* llvm::ConstantArray::get(llvm::ArrayType*, llvm::ArrayRef<llvm::Constant*>)
/usr/local/include/llvm/Constants.h:354:20: note:   candidate expects 2 arguments, 3 provided
make[2]: *** [compiler/IR/CMakeFiles/rphp-llvm-ir.dir/pIRHelper.cpp.o] Error 1
make[1]: *** [compiler/IR/CMakeFiles/rphp-llvm-ir.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by sebastianbergmann** [comment]
It works fine with LLVM 3.0.

**Comment by weyrick** [comment]
Thanks Sebastian. Yes I'd like to keep it only as current as the latest stable release. I've updated the README to reflect version 3.0.
