### ISSUE TITLE
Build with current LLVM fails due to missing llvm/System/Path.h

### ISSUE THREAD

**Issue by sebastianbergmann** [weyrick/roadsend-php-raven#2]
`llvm/System/Path.h` does not exist anymore in current versions of LLVM:

```
[ 79%] Building CXX object compiler/IR/CMakeFiles/rphp-llvm-ir.dir/pGenSupport.cpp.o
/usr/local/src/raven/compiler/IR/pGenSupport.cpp:39:30: fatal error: llvm/System/Path.h: No such file or directory
compilation terminated.
make[2]: *** [compiler/IR/CMakeFiles/rphp-llvm-ir.dir/pGenSupport.cpp.o] Error 1
make[1]: *** [compiler/IR/CMakeFiles/rphp-llvm-ir.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by weyrick** [comment]
Yes, this hasn't been looked at in awhile. But I don't think it will take that much to get it working on the latest versions of things, and it may be fun so I'll give it a shot when I get a moment.

**Comment by weyrick** [comment]
Now compiles with llvm 3.0
